microsoft/vscode-languageserver-node

README.md
server/bin/installServerIntoExtension

This fixes some tiny mistakes in the readme and text output.

Fix small typos

---

server/bin/installServerIntoExtension

This PR removes an unused function from the script and adds a missing `var` keyword.

Cleanup "installServerIntoExtension" script

---

jsonrpc/src/main.ts

Noticed that they're missing from the main export - could we add them?

export SocketMessage reader/writer

---

types/src/main.ts

This pull request fixes a few typos introduced in cad65160940993c2804452718d2085395274e97e.

Fix a few small typos

---

jsonrpc/src/main.ts
protocol/src/protocol.ts
server/src/main.ts
types/src/main.ts

This does nothing but fix a bunch of typos found in the repo.

Typo fixes

---

jsonrpc/src/messages.ts

Resolve #340

---

README.md

See https://github.com/Microsoft/vscode-languageserver-node/pull/441#discussion_r242075128

mention `npm run symlink` in the readme

---

server/src/test/textdocuments.test.ts
textDocument/src/main.ts
textDocument/src/test/textdocument.test.ts

Remove the TextDocumentsConfiguration
Servers can then do `const documents = new TextDocuments(TextDocument)`

add TextDocument.update

---

protocol/src/protocol.semanticTokens.proposed.ts

"know by" is grammatically incorrect so it has been reworded.

Reword type and modifier descriptions

---

jsonrpc/src/common/messageReader.ts
jsonrpc/src/common/messageWriter.ts

Document MessageReader/MessageWriter interfaces

---

client/src/common/client.ts

Implements https://github.com/microsoft/vscode-languageserver-node/issues/418

Expose restartTimes to client.

---

build/azure-pipelines/win32/build.yml

Adding rich navigation to pipeline for Dirk! If this adds too much time, we can separate this into another pipeline

Add Rich Navigation to CI

---

jsonrpc/README.md

fix https://github.com/microsoft/vscode-languageserver-node/issues/759

fix import of jsonrpc module

---

textDocument/src/main.ts
types/src/main.ts

fix: modify some comments in jsdoc

---

client/src/common/foldingRange.ts
protocol/src/common/protocol.foldingRange.ts
types/src/main.ts

https://github.com/microsoft/language-server-protocol/issues/1426

Add collapsedText to FoldingRange

---

protocol/metaModel.json
protocol/src/common/protocol.$.ts
tools/src/visitor.ts

Fix meta model

---

protocol/metaModel.json
tools/src/visitor.ts

Fix varios issue with the meta model generation

Fix meta model implementation

---

client/src/common/diagnostic.ts

cleanup diagnostics in DiagnosticRequestor

---

client/src/common/diagnostic.ts

Nit fixes in the JSDocs of the pull diagnostics client API.

Fix JSDoc typos

---

jsonrpc/src/browser/main.ts
jsonrpc/src/node/main.ts
jsonrpc/src/node/test/connection.test.ts

Add message port support to browser and node implementation.

Add message port support

---

client/src/common/client.ts
jsonrpc/src/common/api.ts
jsonrpc/src/common/connection.ts
jsonrpc/src/node/test/connection.test.ts

There was a bug in #942
I ran the tests via `npm run rebuildAll`

Add messageStrategy connection option

---

client/src/common/diagnostic.ts

Fixes #1092: Confusion about the return values of DiagnosticPullOptions

---

protocol/src/common/protocol.configuration.ts

Fixes #1103: why workspace/configuration params is not matched with spec?

---

client/src/common/client.ts
client/src/common/features.ts
client/src/common/textSynchronization.ts

Fixes #1105: didChange is being sent before didOpen

---

protocol/metaModel.json
protocol/src/common/protocol.ts

Fixes #1125: [Question] "trace" value in metaModel seems wrong?

---

client/src/common/diagnostic.ts
testbed/client/src/extension.ts
testbed/package.json

Fixes #1128: JSON no diagnostics

---

protocol/metaModel.json
tools/src/visitor.ts

Fixes #1609: Meta Model: LSPObject definition does not match the spec

---

client/src/common/client.ts

Fixes #1057: Consider allowing suppression of CloseAction error/info message

---

client/src/common/client.ts
protocol/src/common/connection.ts
server/src/common/server.ts

Fixes #1130: Make protocol connection type safe for sendRequest and sendNotification

---

client-node-tests/src/integration.test.ts
client/src/common/client.ts
client/src/node/main.ts

Fixes #1090: Return Promise from ErrorHandler.closed()

---

client-node-tests/src/workspaceFolder.test.ts
client/src/browser/main.ts
client/src/common/client.ts
client/src/node/main.ts

Fixes #1086: getLocale in the Web version

---

protocol/src/common/protocol.fileOperations.ts

Fixes #992: Can initial contents of a document be set through willCreateFiles response WorkspaceEdit?

---

client/src/common/features.ts

Fixes #1060: documentSelector from server capability have lower priority

---

client/src/common/codeAction.ts
client/src/common/codeConverter.ts
client/src/common/diagnostic.ts
client/src/common/selectionRange.ts

Fixes #1228: Suspicious order of events

---

client/package.json
client/src/common/diagnostic.ts
protocol/src/common/protocol.ts
testbed/workspace/test.txt

Fixes #1233: [css] css language server gets diagnostic pull requests for non-css files

---

server/src/common/server.ts

Fixes #1247: Arrow function erroneously uses the arguments object

---

client-node-tests/package-lock.json
client-node-tests/package.json
client/package-lock.json
client/package.json
client/src/common/client.ts
client/src/common/protocolConverter.ts

Fixes #1258: Support list of commands for trusted markdown.

---

client/src/node/main.ts

Fixes #1313: Capture the exit code of a server process and print it to the log.

---

jsonrpc/src/common/api.ts

Fixes Missing exported types from jsonrpc encoding #1292

---

README.md
types/src/main.ts

Fixes #1102: Add CodeActionKind.RefactorMove

---

client-node-tests/src/converter.test.ts
client/src/common/codeConverter.ts
types/src/main.ts

Fixes #1371: InlineCompletionContext.SelectedCompletionInfo.range is a JavaScript Array at runtime (type mismatch)

---

protocol/metaModel.json
types/src/main.ts

Fixes: #1375: metaModel has mismatched backticks/quotes

---

protocol/src/common/protocol.ts

Fixes #1623: Make the regular expression engine table into a namespaced kind type

---

jsonrpc/src/common/api.ts
jsonrpc/src/common/connection.ts
protocol/metaModel.json
tools/src/visitor.ts

Fixes #1861: MetaModel: Missing Types and TraceValue vs TraceValues

---

client/src/common/client.ts
jsonrpc/src/common/connection.ts
jsonrpc/src/node/test/connection.test.ts

Fixes #1282: Cancellation is missed for already cancelled tokens

---

protocol/metaModel.json
protocol/src/common/protocol.ts

Fixes #1401: Meta model missing references TraceValue vs TraceValues

---

.vscode/launch.json
client/src/common/notebook.ts

Fixes #1394: Unexpected textDocument/didOpen for notebook cell after workspace changed to untrusted

---

types/src/main.ts

Fixes https://github.com/microsoft/vscode-languageserver-node/pull/1343#discussion_r1455720754

Allow undefined snippet edit annotation ID

---

client-node-tests/src/integration.test.ts
client-node-tests/src/servers/testServer.ts
server/src/common/progress.ts

Round progress percentage according to the spec

---

client/src/common/diagnostic.ts
jsonrpc/src/common/connection.ts
jsonrpc/src/node/test/connection.test.ts
protocol/src/common/protocol.diagnostic.ts
protocol/src/common/protocol.ts
testbed/client/src/extension.ts

This pull request adds support for limiting parallelism when processing requests and notifications. It also adds support for pulling on focus change.

Add support for limiting parallelism and pull on focus change

---

client/package.json

This pull request updates the version number for the client from 9.0.2-next.1 to 10.0.0-next.1.

Update version number for client

---

client/src/common/client.ts
client/src/common/diagnostic.ts
client/src/common/features.ts

Fixes #1471: Incorrect handling of diagnostic pull request cancellation

---

jsonrpc/src/common/connection.ts

Fixes #1474: Race condition in sendRequest in jsonrpc

---

client-node-tests/package-lock.json
client-node-tests/package.json
client-node-tests/src/converter.test.ts
client/package-lock.json
client/package.json
jsonrpc/package-lock.json
jsonrpc/package.json
jsonrpc/src/node/test/messages.test.ts
protocol/package-lock.json
protocol/package.json
server/package-lock.json
server/package.json
types/package-lock.json
types/package.json

Merge release into main

---

README.md
client/src/common/client.ts
package-lock.json
package.json
protocol/src/common/protocol.showDocument.ts

Fixes #1488: _WindowMiddleware - wrong definition for showDocument

---

protocol/metaModel.json
tools/src/metaModel.ts
tools/src/visitor.ts

Fixes #1278: Type descriptions in metaModel has types that are not in the metaModel

---

protocol/metaModel.json
tools/src/metaModel.ts
tools/src/visitor.ts

Fixes #1204: Support more than one since tag in the meta model

---

client/src/common/notebook.ts
testbed/workspace/bug.ipynb

Fixes #1525: notebook event is broken. (re-ordering cells)

---

client-node-tests/package-lock.json
client-node-tests/package.json
client/package-lock.json
client/package.json
protocol/package-lock.json
protocol/package.json
server/package-lock.json
server/package.json

Merge release into main.

---

client/src/common/client.ts

Fixes #1548: Extra true in the output log when a language server disconnects

---

client/src/common/fileOperations.ts

Fixes #1581: Client error 'Failed to determine file type' after undoing rename with Cmd+Z

---

protocol/metaModel.json
protocol/src/common/protocol.ts

Follow-up of https://github.com/microsoft/vscode-languageserver-node/pull/1591.

Fix text document didOpen/didClose server capabilities
