microsoft/vscode-languageserver-node

- client/src/main.ts
Prior to this change, child process stderr was discarded, which makes
it hard to debug language server processes. (You can make them log to
a separate file or use the window/logMessage method, but in general
it's hard to guarantee that all output, including crash stack traces,
goes through a user-defined stream in a program.)
This change appends child process stderr output to the output channel.
Clients can suppress this behavior by setting the server's
Executable.stdio 3rd element to be "ignore" (per the Node.js spec).
Fixes #82
> Print child process stderr to output channel

- jsonrpc/src/messageReader.ts
messageBuffer.append creates a buffer based on the length of the string to be written to it. `str.length` does not return the correct length of the string in bytes when the string contains multi-byte unicode characters. Buffer.byteLength does return the proper length, so switched to this method.
> MessageBuffer.append: length of string in bytes

- client/src/main.ts
Previously, only the first argument was passed.
> client: Pass all arguments to ExecuteCommandRequest

- client/src/main.ts
This fixes a bug where `env` was not being propagated to spawned server instances.
I was debugging why my user-defined `env` object was not being passed down to my spawned language server and noticed the missing return value, resulting in `undefined` being passed down the chain.
> Add return value to getEnvironment().

- server/bin/installServerIntoExtension
This PR, when a shrinkwrap file is provided as `argv[5]` and this exist, will make sure that file gets copied so I can lock down my dependencies in both client and server installations and have a 100% reproducible environment in my local development experience.
This should become a best practise, worth mentioning in the documentation.
> Detect and copy npm-shirkwrap file if present

- jsonrpc/src/main.ts
- jsonrpc/src/test/connection.test.ts
Falsy parameter values were translated to `null`. This change fixes that.
> Only convert `undefined` argument to null (fixes #215)

- protocol/src/main.ts
- server/src/main.ts
Reading through the code, I found a typo in one of the object names.  It's unclear to me how far outside of this project this might extend, however.  Please let me know if there is any more work around this.
> Renaming ProtocolConnetion to ProtocolConnection

- client/src/client.ts
- client/src/test/servers/testInitializeResult.ts
Not sure if this is the right way of going about it but it does address#263.
> Specify that the workspace.applyEdit feature is enabled in the client

- server/src/main.ts
related to https://github.com/Microsoft/vscode-languageserver-node/issues/274
> Document that onWillSave handler capabilities reqs

- protocol/src/protocol.implementation.proposed.md
The new `protocol.implementation.proposed.md` file has a few minor English mistakes that needs to be fixed up.
> Correct some grammar and typos

- types/src/main.ts
TextEdit's `insert` function has a documented parameter name that doesn't match the actual parameter's name.
> Fix a parameter typo

- client/src/client.ts
- client/src/test/servers/testInitializeResult.ts
https://github.com/Microsoft/vscode-languageserver-node/blob/f4595fa4f3a52c9210792c7b412f9e2ee478cdd3/client/src/client.ts#L2945-L2955
As seen in the code above, we can see that `documentChanges` are supported and are handled by the VS Code LSP client. However, this capability is not stated in the initialization parameters that the LSP client sends to a language server. It used to be sent but it was [commented out](https://github.com/Microsoft/vscode-languageserver-node/commit/863685b0dc160345bb91d7f7bac84cc6b89d8153#diff-79d1f5abc1a9f55a0e9eae588a7fdd56) and [later removed](https://github.com/Microsoft/vscode-languageserver-node/commit/4bc789ecfca9af5f98188e42ee3302dae2b2a5aa#diff-79d1f5abc1a9f55a0e9eae588a7fdd56). This is basically the same problem as #263 just for a different …
> Client does not declare that clientCapabilities.workspace.workspaceEdit.documentChanges is supported

- protocol/src/protocol.ts
It's currently not possible to register for `workspace/didChangeWatchedFiles` notifications because it has `void` set as a parameter. We should be using `DidChangeWatchedFilesRegistrationOptions` instead so that servers can define the interested files when sending its `client/registerCapability` request to the client.
> Fix registration parameters for workspace/didChangeWatchedFiles

- client/package.json
- client/src/client.ts
- client/src/protocolConverter.ts
- protocol/src/protocol.ts
- types/src/main.ts
This PR implements support for multi-location diagnostics.
I used https://github.com/kieferrm/lsp-dev-setup to setup the experimentation environment.
> Support for multi-location diagnostics

- client/src/client.ts
- client/src/test/integration.test.ts
- client/src/test/servers/testInitializeResult.ts
It is currently not possible for a client to inspect the contents of the `textDocument/publishDiagnostics` notifications from the server before letting VS Code handle them. This pull request introduces a middleware function to allow clients to intercept the contents of the notification before passing them off to VS Code.
> Add middleware to intercept textDocument/publishDiagnostics

- .travis.yml
- package-lock.json
- package.json
In npm 5 (which is included in Node.js 8), symbolic links in the `node_modules` folder are now replaced by what's in the npm registry. This means that symbolic links that were originally created in `.travis.yml` prior to invoking `npm install` were getting deleted and replaced by packages from the npm registry. As a result, we now need to create the symbolic links **after** `npm install` has completed.
Pushing the linking magic down to an npm script instead of only performing this as part of the CI build also allows it to be reused for local development. This has the advantage of making local development more closely match what is happening in the CI builds.
> Replace symlinking in Travis build with npm scripts

- server/src/main.ts
As the [documentation of `TextDocuments#get(uri: string)` funtion](https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L203-L212) states:
> Returns the document for the given URI. Returns undefined if the document is not mananged by this instance.
The return type does not reflect that it can return `undefined`. This commit adds that.
This might be a breaking change for existing code bases (which use `strictNullChecks`), so feel free to reject this PR.
> Add `undefined` to TextDocuments#get(uri: string)

- client/src/client.ts
- protocol/src/protocol.ts
- types/src/main.ts
I've added a new boolean `deprecated` property both `CompletionItem` and `SymbolInformation`.
See Microsoft/language-server-protocol#139.
> Add deprecated boolean property to CompletionItem and SymbolInformation

- client/src/codeConverter.ts
- client/src/protocolConverter.ts
- client/src/protocolDocumentLink.ts
- types/src/main.ts
The current definition of a `DocumentLink` makes resolving a link with `documentLink/resolve` essentially impossible. With only a `range` field available, it is not possible for the server to deduce what the originating content is as it does not have any information as to which text document the link is for.
To correct this, a new `data` field has been introduced to `DocumentLink` that servers can fill in with some whatever it needs when initially fulfilling the `textDocument/documentLink` request. This way, a subsequent `documentLink/resolve` request will have the necessary contextual information available to resolve the link and return back a URI to use in the `target` field.
> Fix documentLink/resolve by introducing a data field

- client/src/client.ts
- client/src/codeConverter.ts
- client/src/protocolCompletionItem.ts
- client/src/protocolConverter.ts
- client/src/test/servers/testInitializeResult.ts
Although VS Code does not currently support appending a visual indicator that a completion item is "deprecated", the `deprecated` property itself of a `CompletionItem` should still be preserved across requests. This will allow language servers to read and write to that field across a `textDocument/completion` request and a `completionItem/resolve` request.
I used `if (x.val === true || x.val === false) { y.val = x.val; }` to ensure that only `boolean` values would be converted as I didn't want to encourage an "anything goes" attitude.
> CompletionItem's deprecated property should be preserved across requests

- types/src/main.ts
- types/src/test/typeguards.test.ts
Also, there was no `TextEdit.is`, which I also added.
Currently, this build fails. If the types package is published, we can remove the definitions in `protocol/src/protocol.colorProvider.ts` and use the ones shipped in `vscode-languageserver-types`.
> Address #362

- client/src/client.ts
- client/src/test/integration.test.ts
- client/src/test/servers/testInitializeResult.ts
- protocol/src/protocol.ts
- server/src/main.ts
Implemented a new `textDocument/resolveRenameLocation` request for preparing and validation before a `textDocument/rename` happens.
This request allows a language server to resolve and validate the current cursor location before a rename is actually attempted. This allows clients to interrupt a rename request if for example the user's text cursor is currently within a language keyword and as such cannot be renamed.
This addresses Microsoft/language-server-protocol#455.
> Add textDocument/prepareRename for preparing a rename request

- client/src/client.ts
- jsonrpc/src/main.ts
- jsonrpc/src/messages.ts
- protocol/src/main.ts
Things I plan to do but haven't done yet:
Questions:
@dbaeumer Would like to get some high-level insight - let me know if this is the right direction, what more things you would want to me to add, etc.
More details are at https://github.com/Microsoft/language-server-protocol-inspector/issues/8
> Introduce Traceformat to allow JSON format log

- jsonrpc/src/messageReader.ts
@dbaeumer `new Buffer()` is deprecated and triggers tons of deprecation warnings in our Electron 3.0.x builds. 
Refs: https://nodesource.com/blog/understanding-the-buffer-deprecation-in-node-js-10/
> avoid deprecated new Buffer() ctor

- client/src/main.ts
- jsonrpc/src/messageReader.ts
- jsonrpc/src/messageWriter.ts
- server/src/main.ts
I've had an issue with an extension that wouldn't load because of a version dependency and a misspelling of the word "received" (as "recevied") in the error message made me go bonkers.
Corrected 5 instances of this misspelling across the project, no functional changes
> Fixed error msg misspellings of "received"

- client/package-lock.json
Spotted while running `npm install` in local development. npm automatically syncs the `package.json` and the lockfile, which creates this change.
The 5.1.1 version bump is from 9c26d2b58a441698a8e7790ce46c667dc4e2e199.
> Update version in lockfile to match package.json

- client/src/codeConverter.ts
It can be useful for users of vscode-languageclient.
> Add asVersionedTextDocumentIdentifier to the Converter interface

- client/src/client.ts
- client/src/implementation.ts
- client/src/protocolConverter.ts
- client/src/test/servers/testInitializeResult.ts
- client/src/typeDefinition.ts
- protocol/src/protocol.implementation.ts
- protocol/src/protocol.ts
- protocol/src/protocol.typeDefinition.ts
- types/src/main.ts
I've updated `textDocument/definition`, `textDocument/implementation`, and `textDocument/typeDefinition`, to potentially return a `DefinitionLink`. This new interface includes metadata about the ranges of both the originating source symbol and the target symbol. This will help provide more context to the user while navigating between different symbols in an editor.
For example, instead of simply highlighting a word, the editor can now understand that the source symbol's range extends beyond standard word boundaries. This will allow it to highlight/underline stuff like an entire `java.util.List` in a Java `import` statement.
This implements Microsoft/language-server-protocol#524.
> Provide metadata about symbols with DefinitionLink

- client/package.json
- jsonrpc/package.json
- protocol/package.json
- server/package.json
- types/package.json
This adds a `directory` field to the `repository` objects in package.json. This is a new field for monorepos specced in this npm RFC: https://github.com/npm/rfcs/blob/d39184cdedc000aa8e60b4d63878b834aa5f0ff0/accepted/0000-monorepo-subdirectory-declaration.md
It enables cross-repository go-to-definition on [Sourcegraph](https://sourcegraph.com), as Sourcegraph can resolve packages to a specific directory in the angular monorepo.
Clients that don't know this field simply ignore it (as with any other arbitrary field in package.json).
> Add repository.directory field to package.json

- protocol/src/protocol.ts
See https://github.com/Microsoft/language-server-protocol/issues/618 and https://github.com/Microsoft/language-server-protocol/pull/637
@dbaeumer
> Add optional reason for why the client failed to apply an edit

- client/src/configuration.ts
When requesting a nested configuration section (e.g. `a.b.c`), the configuration returned isn't scoped to the requested uri, although it does so when requesting something like `a`, with no dot inside.
> Fix configuration not always using resource scope

- client/src/client.ts
This allows setting `traceOutputChannelName` in the `LanguageClientOptions` to use a different output channel. Otherwise, this falls back onto the default output channel. `traceOutputChannel` can also be set directly.
Just a note: The current formatting settings are not actually consistently applied on all of the files, so I have been caught out by format on save whilst creating this PR.
TODO: test this - I couldn't get `npm` to work properly (it was giving me really obtuse error messages) when I tried to install my local copy of the client into an extension. (@matklad, how did you do it?)
TODO: determine if the output channel should be automatically shown. My inclination is to say not, but I'm not sure.
> Support using a seperate output channel for trace messages

- protocol/src/protocol.ts
We have a variety of experimental capabilities that we add using the `ServerCapabilities` type, but are unable to type them nicely because `experimental` is typed as `any`. By adding this generic, it would enable people to reuse this type, without having to hack around the `any`, without changing how any back-compatibility of existing code works (I think).
Thoughts?
> Add generic capabilities type

- protocol/src/main.ts
- protocol/src/protocol.callHierarchy.proposed.md
- protocol/src/protocol.callHierarchy.proposed.ts
This PR proposes a `textDocument/callHierarchy` request sent from the client to the server to request the call hierarchy for a symbol at the given text document position.
A prototype implementation for TypeScript LS is implemented in https://github.com/theia-ide/typescript-language-server/pull/98.
Related LSP issue: https://github.com/Microsoft/language-server-protocol/issues/468
> Add proposed `textDocument/callHierarchy` extension

- server/src/main.ts
Implementation and type definition requests can return `DefinitionLink[]`, can't they?
> onImplementation and onTypeDefinition can return DefinitionLink[]

- client-tests/package-lock.json
- client-tests/package.json
- client-tests/src/workspaceFolders.test.ts
- client/package-lock.json
- client/src/workspaceFolders.ts
This is a fix for 
Workspace folder changes are not sent to the server if they occur during initialisation #451
The gist of the fix is to remember the workspace folders sent to a language server during the "initialize" call and then send the diff between that state and the current WS folders when registering the workspace change listener.
Signed-off-by: Thomas Mäder <tmader@redhat.com>
> Send workspace folder diff upon listener notification

- textDocument/src/main.ts
Having 'update' on the new vscode-languageserver-textdocuments.TextDocument makes it hard to adopt for existing client that have a TextDocument in their API.
e.g. https://github.com/microsoft/vscode-json-languageservice/blob/1eca6c2ee964be30a3a0d7c3b3fc8ba234be265b/src/jsonLanguageService.ts#L32
It's a breaking change that will then also ripple through to all client of the service
> remove update from types

- client/src/semanticTokens.proposed.ts
The client capability is sending back `Proposed.SemanticTokenTypes.comment` two times. I am assuming this is wrong...
> Remove duplicated semantic token type

- client/src/semanticTokens.proposed.ts
Changes `asLedgend` to `asLegend`.
> Fix small typo in function name

- jsonrpc/src/test/connection.test.ts
- jsonrpc/src/test/customCancellationStrategy.ts
2 unit tests. one for regular cancellation (default) and one to test custom cancellation strategy
> added cancellation tests in json rpc

- jsonrpc/src/common/connection.ts
- jsonrpc/src/common/messages.ts
The `id` and `params` fields of a JSON-RPC request were not typed consistently with [the JSON-RPC spec for request objects](https://www.jsonrpc.org/specification#request_object).
In particular:
1. `id` *may* be `null` (although such would be quite bizarre)
1. `params` *must* be omitted (i.e. _not_ null) or an array or an object. It may *not* be a number or a string.
> Expand/restrict types per the JSON-RPC spec

- jsonrpc/src/common/connection.ts
Aligns the server with microsoft/language-server-protocol#953
> Aligns language server with protocol proposition

- client-node-tests/src/integration.test.ts
- client-node-tests/src/servers/testServer.ts
- client/src/common/client.ts
- protocol/src/common/protocol.progress.ts
@dbaeumer I think this is working as expected now, however I have some type errors I can't figure out how to resolve:
> Add support for middleware in onProgress

- client/src/common/codeConverter.ts
Have FileFormattingOptions in asFormattingOptions to make clear what settings are expected.
I tested that `vscode.workspace.getConfiguration('files').trimFinalNewlines` works.
> FileFormattingOptions for asFormattingOptions

- protocol/src/common/protocol.ts
According to the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize), the `moniker` property of the `TextDocumentCapabilities` may be undefined as all the other capabilities. Perhaps, the omission of the optionality marker here is a typo.
> Make the moniker capability optional as per the spec

- client-node-tests/src/integration.test.ts
- client-node-tests/src/servers/crashOnShutdownServer.ts
- client/src/common/client.ts
LanguageClient#stop sends a shutdown request to the language server. If
the server crashes/exits before sending a response, the promise returned
by LanguageClient#stop never settles. This happens because the
disconnect event is ignored during shutdown.
Fix the hang by not ignoring disconnects during shutdown. This will
cause LanguageClient#stop to throw an exception ("Connection got
disposed") if the server crashes or exits unexpectedly during shutdown.
> Fix hang when server crashes during shutdown

- types/src/main.ts
Minor, fixes a broken markdown link in the documentation of `CompletionItem.data`:
> Fix broken doc markdown link

- client/src/common/client.ts
- jsonrpc/src/common/connection.ts
- protocol/src/common/connection.ts
Currently the exit notification is not sent because the connection gets closed before the message is sent (at least on my machine in WSL). This change waits for the exit notification to be sent before closing the connection.
Fixes #726 (exit notification not received part).
> Ensure exit notification is sent before closing connection

- client/src/common/client.ts
Take into account the user choice and only open the output channel if
user has clicked "Go to output".
Fixes #786
> Fix "A request has failed" dialog that can not be dismissed

- client/src/common/protocolConverter.ts
This is a follow-up of https://github.com/microsoft/vscode/issues/136618
`location` of `SymbolInformation` is lost in the deprecated `vscode.SymbolInformation` constructor that is used here:
https://github.com/microsoft/vscode-languageserver-node/blob/859a8ece3e14b130d531c6102b2d108196436bc4/client/src/common/protocolConverter.ts#L816-L819
This is only a problem if `range` is not defined in which case vscode will not display the symbol in the symbol picker. The `range` needs to be falsy in order to use [resolveWorkspaceSymbol](https://github.com/microsoft/vscode/blob/2c083a7bc92a86077f32a0d700c3821b76372e62/src/vs/vscode.d.ts#L3151)
To override `resolveWorkspaceSymbol`, I used the following code:
```
const feature = this.languageClient.getFeature('workspace/symbol');
const provider: …
```
> Location of SymbolInformation gets lost when range is not defined

- jsonrpc/package.json
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
Optional chaining is supported by Node 14+.
> correct engines field node 14+

- client/src/node/main.ts
> feat: more descriptive error when childProcess.spawn fails

- types/src/main.ts
The hover documentation for `interface MarkupContent` isn't aligned; converting tabs to spaces appears to fix its formatting.
> convert tabs to spaces to fix improper indentation

- client/src/common/fileSystemWatcher.ts
I looked through vscode's code base and It doesn't look like ```fileSystemWatcher.dispose()``` through ```disposables.push(fileSystemWatcher);``` will unsubscribe each file watch subscription. 
each must be disposed individually by ```this.hookListeners(fileSystemWatcher, watchCreate, watchChange, watchDelete, **disposables**);``` like how ```registerRaw``` does.
here are relevant code in vscode
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostFileSystemEventService.ts#L22
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostFileSystemEventService.ts#L91
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/event.ts#L617
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/event.ts#L681 …
> make sure to unsubscribe from file events

- protocol/metaModel.json
- protocol/src/common/protocol.workspaceFolder.ts
The LSP spec defines these as optional:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initializeParams
Fixes one of the issues in https://github.com/microsoft/vscode-languageserver-node/issues/946.
> Mark WorkspaceFoldersInitializeParams.workspaceFolders as optional

- client/src/common/client.ts
If there is an error during `showDocument` execution, it sounds like the request should return `success: false`. On the other hand if this is intentional, feel free to close.
> fix: return `false` when `showDocument` fails

- protocol/metaModel.json
- tools/src/visitor.ts
@dbaeumer feel free to close this if you're already looking at it (or it's not the right fix). I don't know why this `.parent` is required, but it appears to fix all of the missing enum docs.
> Fix meta model documentation for enum values

- protocol/src/common/protocol.callHierarchy.ts
- protocol/src/common/protocol.diagnostic.ts
- protocol/src/common/protocol.fileOperations.ts
- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.inlayHint.ts
- protocol/src/common/protocol.notebook.ts
- protocol/src/common/protocol.showDocument.ts
- protocol/src/common/protocol.ts
- protocol/src/common/protocol.workspaceFolder.ts
- server/src/common/notebook.ts
- server/src/common/textDocuments.ts
- textDocument/src/main.ts
- types/src/main.ts
This is mostly typos and tweaks I noticed when diffing code generated from parsing the TypeScript spec to the new meta model, but also some additional things I spotted along the way.
Some of the changes are quite trivial like trailing full stops.. I mostly added these where they existed in the LSP spec (in an attempt to reduce the size of my diff to help me review the TS -> meta model migration), I didn't try to fix these in all places.
@dbaeumer
> Fix typos + minor doc tweaks

- types/src/main.ts
```Is.defined``` cant't cover ```null```, ```Location.is(value)``` will npe when value is null.
> fix: Location & LocationLink#is npe.

- protocol/src/common/messages.ts
- protocol/src/common/protocol.$.ts
- protocol/src/common/protocol.callHierarchy.ts
- protocol/src/common/protocol.colorProvider.ts
- protocol/src/common/protocol.configuration.ts
- protocol/src/common/protocol.declaration.ts
- protocol/src/common/protocol.diagnostic.ts
- protocol/src/common/protocol.fileOperations.ts
- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.implementation.ts
- protocol/src/common/protocol.inlayHint.ts
- protocol/src/common/protocol.inlineValue.ts
- protocol/src/common/protocol.linkedEditingRange.ts
- protocol/src/common/protocol.moniker.ts
- protocol/src/common/protocol.notebook.ts
- protocol/src/common/protocol.progress.ts
- protocol/src/common/protocol.selectionRange.ts
- protocol/src/common/protocol.semanticTokens.ts
- protocol/src/common/protocol.showDocument.ts
- protocol/src/common/protocol.ts
- protocol/src/common/protocol.typeDefinition.ts
- protocol/src/common/protocol.typeHierarchy.ts
- protocol/src/common/protocol.workspaceFolder.ts
- tools/src/metaModel.ts
Fixes #998.
It would be good to get the info checked! I went through and everything that said it's sent from the server got `serverToClient`, `progress` and `cancelRequest` got `both`, and everything else got `clientToServer`.
> Add information about message direction to metamodel

- protocol/metaModel.json
- protocol/src/common/protocol.typeDefinition.ts
`TextDocumentPositioParams` -> `TextDocumentPositionParams`
> Fixed a typo

- textDocument/src/main.ts
I thought the documentation was a bit unclear what this method did, after some exploration locally I added some more documentation to the documentation field.
> Add example to positionAt

- client/src/common/client.ts
Some language servers and vscode have a bit different ways to encode uri to string. For example [csharp-language-server-protocol](https://github.com/OmniSharp/csharp-language-server-protocol) encodes uri `C:\abc` to `file:///c:/abc` but vscode encodes this uri a bit more aggressive: `file:///c%3A/abc`. As a result we have a problem with lookup in a map in the method `handleApplyWorkspaceEdit`. To fix it I am going to call converter `asUri` before call map lookup by uri.
> A more reliable way to check the document version when handling ApplyWorkspaceEdit

- jsonrpc/src/common/cancellation.ts
- protocol/src/common/protocol.colorProvider.ts
- protocol/src/common/protocol.declaration.ts
- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.implementation.ts
- protocol/src/common/protocol.inlayHint.ts
- protocol/src/common/protocol.inlineValue.ts
- protocol/src/common/protocol.moniker.ts
- protocol/src/common/protocol.selectionRange.ts
- protocol/src/common/protocol.ts
- protocol/src/common/protocol.typeDefinition.ts
- server/src/common/server.ts
- server/src/node/main.ts
- textDocument/src/main.ts
- types/src/main.ts
Fixes #1015
Converts the jsdoc comments to use `@link` syntax for links. This makes these links work inside editors like VS Code
> Adopt `@link` for jsdoc comments

- server/src/common/server.ts
The feature works fine, but TypeScript is unaware that the response is allowed. Sync with `protocol.ts`:
https://github.com/microsoft/vscode-languageserver-node/blob/c91c2f89e0a3d8aa8923355a65a2977b2b3d3b57/protocol/src/common/protocol.ts#L3623
Background: https://github.com/microsoft/vscode/issues/85157#issuecomment-688111130
> Add defaultBehavior response to onPrepareRename

- client/src/common/client.ts
- protocol/src/common/protocol.ts
As mentioned in https://github.com/microsoft/vscode-languageserver-node/issues/1101, currently there is no way to intercept `client/registerCapability`/`client/unregisterCapability`. This PR adds both of these requests to the middleware.
Not entirely sure if if these calls should be placed directly in `_Middleware` so any help is appreciated 🙏
> Added registerCapability and unregisterCapability to the client middleware

- textDocument/src/main.ts
> Fixes #1199: Clarify Spec regarding default behavior for Position.line containing an out-of-range value

- client-node-tests/src/integration.test.ts
- client/src/common/client.ts
Closes #918
Allow adding a general middleware `provideRequestOrNotification` to client options that is used for all requests and notifications. The attached issue has a bit more context, but this is useful for measuring performance and even appending additional parameters to requests if desired.
Please let me know if this is the right direction for the implementation and if I'm following the right style and naming conventions. I wasn't sure if this was the right level for the implementation, but the general middleware can alternatively be implemented as a connection option instead.
> Implement general middleware for requests and notifications

- jsonrpc/src/common/connection.ts
- protocol/src/common/messages.ts
> Fixes #1231: Setting exactOptionalPropertyTypes results in TS2720 errors in vscode-languageserver-protocol

- protocol/src/common/protocol.ts
The existing example led me to incorrectly try something like`*.{ts,js}`, which won't ever match anything: it's `**/*.{ts,js}`.
I updated with the more useful example (though note, just like the comment above, I had to insert a nbsp because JS grammar).
> Refer to TextDocumentFilter for glob format on pattern field

- protocol/metaModel.json
- protocol/src/common/protocol.ts
> Fixes #1293: metamodel documentation strings contains unmatched back-ticks

- client/src/common/client.ts
- client/src/common/configuration.ts
- client/src/common/diagnostic.ts
- client/src/common/executeCommand.ts
- client/src/common/features.ts
- client/src/common/fileOperations.ts
- client/src/common/fileSystemWatcher.ts
- client/src/common/notebook.ts
- client/src/common/progress.ts
- client/src/common/textSynchronization.ts
- client/src/common/workspaceFolder.ts
- testbed/client/src/extension.ts
- testbed/server/src/server.ts
> Fixes #1295: No LSP workspace/didChangeConfiguration notifications after language server restart

- client/src/common/foldingRange.ts
- protocol/metaModel.json
- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.ts
- server/src/common/foldingRange.ts
- server/src/common/server.ts
Relating to #1306
server.ts has `onFoldingRanges` already which I've left alone for backwards compatibility but this PR also adds `languages.foldingRange.on` which should be identical.
> Add the workspace/foldingRange/refresh method

- textDocument/package.json
- types/package.json
up until the addition of "exports", bundlers found the root "module" field and resolved the the esm version.
this change fixes a regression from https://github.com/microsoft/vscode-languageserver-node/pull/1297 where cjs browser consumers now get resolved to the umd, getting a warning about dynamic require.
> fix: ensure bundlers pick up esm version

- .vscode/settings.json
- client/src/common/codeAction.ts
> Fixes #1359: codeAction.resolveSupport does not have command field to detect support, but it supports it

- client/src/common/executeCommand.ts
- client/src/common/features.ts
- client/src/common/fileSystemWatcher.ts
- client/src/common/notebook.ts
The `DynamicFeature.unregister(id)` method is supposed to dispose the specified provider and delete it from the feature. In some implementations the provider is not actually deleted and stays in the storage forever. This PR fixes this.
> Always delete feature providers in `unregister()`

- client/src/node/main.ts
Previously any exit code (even 0), were logged as error messages. Now successful exits are instead logged as an information message.
For more information see:
- [Commit](https://github.com/microsoft/vscode-languageserver-node/commit/c6817d36ffbc9efb17330b19e5e73a2caaa197d9) where exit code capturing was added.
> Changed Successful Exit Notification for Node Client

- client-node-tests/src/helpers.test.ts
- client/src/common/client.ts
- client/src/common/protocolConverter.ts
- protocol/src/common/protocol.ts
- types/src/main.ts
Adding support for snippet workspace edits.
Closes [#724](https://github.com/microsoft/language-server-protocol/issues/724)
> Snippet edit feature

- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.inlayHint.ts
- protocol/src/common/protocol.notebook.ts
- protocol/src/common/protocol.semanticTokens.ts
- protocol/src/common/protocol.ts
- types/src/main.ts
These don't change the semantics of the protocol. Marking these as proposed makes it harder for tools that process the metamodel to omit proposed items.
> Remove proposed tags from new names for structure literals

- textDocument/package.json
- types/package.json
The `module` export condition is an unofficial export condition that’s respected by bundlers. It tells the bundler to resolve to an entrypoint, regardless of whether a module is imported or `require`d. This avoids the [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard).
This was the original intent of the `browser` condition when it was added in https://github.com/microsoft/vscode-languageserver-node/pull/1326.
Thanks for telling me this @Andarist
> Use module export condition for types and textdocument

- .vscode/settings.json
- client/src/common/client.ts
- client/src/common/protocolConverter.ts
This pull request fixes the issue #1414 by updating the ProtocolConverter#asWorkspaceEdit method to correctly support workspace edits with snippets. The changes include updating the VS Code version to 1.86, adjusting the package.json file, and modifying the code in the protocol converter to construct VS Code text edits for SnippetTextEdit. The converted edits are maintained in an array and then set using the result.set method.
> Fix ProtocolConverter#asWorkspaceEdit to correctly support workspace edits with snippets

- types/src/main.ts
As a maintainer of the Haskell language server, I would like to be able to name my language :D
> Add Haskell to LanguageKind

- client/src/common/textSynchronization.ts
Note: all other features follow the same practice in their `unregister()` methods -- if the features doesn't exist, do nothing and don't throw errors.
> Don't crash when unregistering a feature that doesn't exist

- client/src/common/api.ts
> Fixes #1468: Missing 'export TypeHierarchyMiddleware' from api.ts

- client/src/common/semanticTokens.ts
- types/src/main.ts
Visual Studio Code has 'label' in its standard token types list. https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers
Fixes #1422
> Add SemanticTokenTypes.label

- build/azure-pipelines/pipeline.yml
This pull request updates the Node.js version to 18.18.2 in order to support the --experimental-fetch feature.
> Update Node.js version to 18.18.2

- client/src/common/client.ts
This sets the language client ID as a fallback for the diagnostics collection name. If no collection name is provided, VSCode generates one. This name is visible in the diagnostics table view of the problems panel.
This can be solved for every language server integration separately, but IMO it’s nicer if this package provides a better default. An alternative is to use the name instead of the ID. I went with ID, because `typescript` in the screenshot is lower case.
> Use client ID as fallback for diagnostics collection

- client-node-tests/src/converter.test.ts
- client/src/common/client.ts
- client/src/common/protocolConverter.ts
VS Code provides `supportThemeIcons` in `MarkdownString` to enable showing icons in contexts like hover, but there's no equivalent support in `LanguageClientOptions` from this library.
cc @lukka @spebl
> Add supportThemeIcons in MarkdownString

- README.md
- jsonrpc/README.md
- protocol/README.md
- server/README.md
- types/README.md
- protocol module's NPM badge link leads to `vscode-languageclient`, not `vscode-languageserver-protocol`
- Current Azure pipeline definition id is 52 (I presume)
- Azure pipeline link in each modules leads to `ms/vscode-languageserver-node`, not `vscode/vscode-languageserver-node`
> Fix npm, azure pipeline links

- client/src/common/client.ts
I've noticed that if a LSP server reports an error via `ResponseError::message` field, it's a bit of a hit or miss if this is reported to the end user in a popup.
For example [rename reports the error in the dialog](https://github.com/SWAT-engineering/vscode-languageserver-node/blob/1f603f4f73552a30a649667262e5f83532cf223e/client/src/common/rename.ts#L112-L116) while errors in many others parts end up in the [generic handler](https://github.com/SWAT-engineering/vscode-languageserver-node/blob/12f4439aa73c31bfe2d4e44377426c23f2a55c01/client/src/common/client.ts#L2053-L2054)
I've changed this such that both the message from the library is kept, while also reporting the message from the LSP server.
> Show the error message from the LSP server

- client-node-tests/src/integration.test.ts
- client/src/common/diagnostic.ts
By not accepting a `resultReporter` parameter in `provideDiagnostics` the `provideWorkspaceDiagnostics` middleware always used the reporter it was initially passed. This means that diagnostics are always reported without the ability to manipulate them first.
> Allow resultReporter to be substituted in provideWorkspaceDiagnostics middleware.

- client-node-tests/src/converter.test.ts
- client/src/common/completion.ts
- client/src/common/protocolConverter.ts
- protocol/metaModel.json
- protocol/src/common/protocol.ts
- types/src/main.ts
Implements the changes in the LSP spec PR at https://github.com/microsoft/language-server-protocol/pull/2018 (see also https://github.com/microsoft/language-server-protocol/issues/1802).
Please let me know if you think there are any additional test cases that need covering.
> Add support for CompletionList "applyKind" to control how defaults and per-item commitCharacters/data are combined

- protocol/metaModel.json
- types/src/main.ts
> Fixes #1565: LanguageKind is marked as proposed and since 3.18, but is referenced from non-proposed TextDocumentItem.languageId

- protocol/metaModel.json
- protocol/metaModel.schema.json
- protocol/src/common/protocol.callHierarchy.ts
- protocol/src/common/protocol.colorProvider.ts
- protocol/src/common/protocol.configuration.ts
- protocol/src/common/protocol.declaration.ts
- protocol/src/common/protocol.diagnostic.ts
- protocol/src/common/protocol.fileOperations.ts
- protocol/src/common/protocol.foldingRange.ts
- protocol/src/common/protocol.implementation.ts
- protocol/src/common/protocol.inlayHint.ts
- protocol/src/common/protocol.inlineCompletion.ts
- protocol/src/common/protocol.inlineValue.ts
- protocol/src/common/protocol.linkedEditingRange.ts
- protocol/src/common/protocol.moniker.ts
- protocol/src/common/protocol.progress.ts
- protocol/src/common/protocol.selectionRange.ts
- protocol/src/common/protocol.semanticTokens.ts
- protocol/src/common/protocol.showDocument.ts
- protocol/src/common/protocol.textDocumentContent.ts
- protocol/src/common/protocol.ts
- protocol/src/common/protocol.typeDefinition.ts
- protocol/src/common/protocol.typeHierarchy.ts
- protocol/src/common/protocol.workspaceFolder.ts
- tools/src/metaModel.ts
- tools/src/visitor.ts
Closes https://github.com/microsoft/language-server-protocol/issues/2059.
> Add capability information to the metamodel

- jsonrpc/src/common/semaphore.ts
Just a small typo in error message in the `Semaphore.doRunNext` method.
> minor typo semaphore.ts

- jsonrpc/src/common/linkedMap.ts
If you try to consume (or build) this library with the latest `lib`, you'll get the following error from TypeScript:
```
node_modules/.pnpm/vscode-jsonrpc@8.2.0/node_modules/vscode-jsonrpc/lib/common/linkedMap.d.ts:29:5 - error TS2416: Property 'keys' in type 'LinkedMap<K, V>' is not assignable to the same property in base type 'Map<K, V>'.
Type '() => IterableIterator<K>' is not assignable to type '() => MapIterator<K>'.
Type 'IterableIterator<K>' is missing the following properties from type 'MapIterator<K>': [Symbol.dispose], map, filter, take, and 9 more.
29     keys(): IterableIterator<K>;
~~~~
```
This is because `Map` now returns a ["richer" iterator object](https://github.com/tc39/proposal-iterator-helpers) with several methods, but `LinkedMap` just returns its own bespoke …
> Use `MapIterator` return types in `LinkedMap` methods.

- protocol/metaModel.json
- protocol/src/common/protocol.colorProvider.ts
Adding the same capability information as `textDocument/documentColor` as this is the corresponding resolve request.
> Add capability information to `textDocument/colorPresentation`
